---
title: "Homework 6"
author: 'Chase Weida; Github: cweida'
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggrepel)
```

### Importing Data
```{r}
data <- readxl::read_xlsx("./Data/KIB - Best in Show (public).xlsx", "Best in show full sheet")
data <- as.data.frame(data)

colnames(data) <- c(as.character(data[3,1]), as.character(data[2,-(1)]))
data <- data[-c(1:3),]
isNaCol <- is.na(colnames(data))
data <- data[,!isNaCol]
isNACol <- c(colnames(data) == "NA")
data <- data[,!isNACol]

data <- data %>% select(c('Dog breed', 'category', `datadog score`, `POPULARITY IN US`, `INTELLIGENCE (TRAINABILITY) ranking`, `size category`)) %>% 
  mutate(`Dog breed` = as.factor(`Dog breed`), 
         category = as.factor(category),
        `size` = factor(`size category`, levels = c('small', 'medium','large')),
        `datadog score` = as.numeric(`datadog score`),
        `Intelligence` = as.numeric(`INTELLIGENCE (TRAINABILITY) ranking`),
        Popularity = as.numeric(`POPULARITY IN US`)) %>%
  mutate(`Intelligence` = as.factor(ifelse(`Intelligence` >= .35, 'clever', 'dumb')))
data['Intelligence']

data <- data %>% select(c("Dog breed", "category", "datadog score", "size", "Intelligence", "Popularity"))

data <- drop_na(data)
```

### Plotting the Data
```{r}
plot <- ggplot(data, mapping = aes(x = `datadog score`,y = Popularity))
plot <- plot + geom_point(aes(size = `size`, color = category, shape = Intelligence)) + scale_size_discrete(range = c(2, 5)) + geom_text_repel(mapping = aes(label = `Dog breed`, color = category), size = 2) 
plot <- plot + ylab('Popularity') + xlab('Dog Data Score')
plot <- plot + ylim(max(data$Popularity), min(data$Popularity)) + geom_hline(yintercept = (mean(data$Popularity))) + geom_vline(xintercept = mean(data$`datadog score`))
plot
```










